apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: krieg
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  secretName: krieg-tls-secret
  commonName: {{ .Values.domain }}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.domain }}
  - "*.{{ .Values.domain }}"
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replication-allowed: "true"
      replicator.v1.mittwald.de/replication-allowed-namespaces: "*"
      replicator.v1.mittwald.de/replicate-to: "*"
