kind: Secret
apiVersion: v1
metadata:
  name: cert-manager-secrets
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api-token: {{ .Values.apiToken }}
