controller:
  nodeSelector:
    role: cp
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "cp"
    effect: "NoSchedule"

speaker:
  nodeSelector:
    role: cp
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "cp"
    effect: "NoSchedule"
