controller:
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "cp"
    effect: "NoSchedule"

speaker:
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "cp"
    effect: "NoSchedule"
