resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
logs:
  general:
    format: json
    filePath: "/var/log/traefik/traefik.log"
  access:
    enabled: true
deployment:
  additionalVolumes:
  - name: traefik-logs
    hostPath:
      path: /var/log/traefik/
      type: Directory
additionalVolumeMounts:
- name: traefik-logs
  mountPath: /var/log/traefik
ports:
  # web:
  #   middlewares:
  #   - network-crowdsec@kubernetescrd
  # websecure:
  #   middlewares:
  #   - network-crowdsec@kubernetescrd
  loki:
    port: 3100        
    expose:
      default: true
    exposedPort: 3100
    protocol: TCP
  prometheus:
    port: 9090
    expose:
      default: true
    exposedPort: 9090
    protocol: TCP
nodeSelector:
  role: cp
tolerations:
- key: "role"
  operator: "Equal"
  value: "cp"
  effect: "NoSchedule"
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.2
