apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: bouncer
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  plugin:
    bouncer:
      enabled: true
      crowdsecMode: stream
      crowdsecLapiScheme: https
      crowdsecLapiHost: crowdsec-service.monitoring:8080
      crowdsecLapiKey: {{ .Values.bouncer.lapiKey }}
