---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: adguard-secrets
  namespace: network
spec:
  encryptedData:
    users.yaml: AgAqPDePpoZ4syqPtI/pOXUBqfzW2f93n+guwtoJVZJdZpe1FBBs7CbtVc4DU+DCCeVkykY9hfIt5+BKf/U1ijc54TixWOuJmRIczM5fOK3CorbgHBMHkY8KrciWcfxiCodUsDRkzO3b7LcWCKWUIWujLgcOsfC7kPY5zWGtehXprJP61IlNbs2MNe8DAlh2atb4HWK6pCaoJFUqX+sOLB02EzR4sFb1TH4YXOWxiCb0Odr3pxt82SUN/4dBdyy3jodlyMWV3Q6T/du4DOH1aI25YzLYnZLruNfyvUX9nNFntMyzmbA4Jj6+BPGDTGMYsFo8HvCmaj55Dn/ehiXqMjL05D60d6L8YNg5WOeEVLpdn/Pc1uoplL7dXPd86ffjzvUNv1vNYw7lEbMXa16D46M7e13Fk/f6UrIATty0O1+5lWAtzQewErv5ZMHWkrGHuuBw7ocJnUU4KEsg6SuzfEqjtyx7GqyVzAKcXdG2iEYsBpEnL4vRJ/9eau5e1h73AM3uW0remC3E1b0hiE3rrzx2FFAaXH5TzbQl8eFhDTCApCnw0S3ApfznAJZ9DkXX/s6lRZiqA7RTf7dSXivfjDmKNbyO20tMQrLm9TgMLmZYzHaL/TLVU8DCWVvT2D4PIN8ru2Ro3S2Dtw76KFN0efGBlZY8LvqBpiozX20OypetJV65qKQAhGRHoSR4ZIDNyXzwMx2fkDQGKc6CYA4XtDY5AKgl4o0f8Ima9NQlOOhx/GHPjNxjGTAXBenNtGHXwipiYcXIwmC3RmtE7IMGPH8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: adguard-secrets
      namespace: network
    type: Opaque
