apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
  namespace: network
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
