---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cert-manager-secrets
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAfWdTNWqevM4uzzN0CcT4F1he5wIK9A9kxGlW+FqyfKCu7HJysaebhFUB/h+AgKcwD86y5l1kYvawSn4j/cv8jjK3URDKb0VYv7EshXbqGMGTGdTHzKsqKxQMTQ5lUUAyCFLmFtHYkwIj+hAxDnibC2MKvK6tF8abM1MVg9w4S45ymKddNOgp22m3BiEJPDvHNc5zt/hEwh6jv8Mob5uzDUPhEtUB6hs/Oc5qmePFQykc9khsNiVC4QhmudzvuH6B4bRofaIJiC3LiyfC2v1QUjBbTnFx/ZdDOISJp7Ma0lwLXYfvRXQyqMDndtjb8O8Zbn6higvYexUHKUHlJ+Ntl5I1pstcJ4wAsKp2wKR4ocKD1pa+pddJyE9cvjVT/pnQNPAdfm59J2CcUIAHqK6eDs6peOBYfPAE2OZkOUdNm7jjLo969dySnS66RAH3DIEFrPJDe74nNoLEUqJNiXpsm/GOmPFtoDou+FED3gFr8I8jtDU8y/o/rW/3SaQ1/PLdlXKH97ZS8HeNzNCvSG7QzNd+Gip2FFNkUqgIjdK2Enxtxild6swgb27lkfYAukCkaapKBYu5mdg6XH7PEPo8ei0MQ5ZS+YBFrLHx+Nr4PECB7Swsz0stqEctgYmej4hCsJK2RoaDc/AZU+LcsWGXWv065i5Bgoa4cpdJliMDW6vZk699dZgWoEkVNxXTXvrVe0hPl6gLV6NjGMrLxXGpCinU/VMT4wNvgzleZbvfFy+P9MxAZnpBS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cert-manager-secrets
      namespace: cert-manager
    type: Opaque
