---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cert-manager-secrets
  namespace: network
spec:
  encryptedData:
    api-token: AgABBGsTZT4wacehU6ixpLXNQeHlC3abz7EpQtOqD8q01hyi8qxBAEjB86C75j/vAHKgpcYTNeuWrdS8AE8BgJ34mpCPF4XJabQs2+q01vQ2GZZF/x2Bm3nUTHG3RRkmswvczB+UhTYZTEi4TQReqEKy2jXXINkokMozxMqz11Ltw5rIZmup83bOcUmgoDBgxMoQQuOXP+g1ro78rxItpRIY0HYmFdqyM1TdjsJD+ml8pa3lJMPcXSDXh2NAOE3faSrlC9Qqv0lP14Q6PZZaC6z85OAq87o/kTScHCPx6g5sraDYxMYInXhaE+SKLRaMzWm54UE09nXcExpWO7i64P98mFm/Eoh6kiU/3ldFeXjCy71gNiFbjs0Uk29UDh2tVCCVdPsO2rCW+DZvBt2QWoy0GSHLuCxBLaVmct+72Vn98RCp8WORtTawj3yiBsVXHDQ2jlrIin429wax53DK5LZaZwuEGK8CJevyCnFc0D9In5u1kOgSEXkJxXJBfEqywbRxtDhDfLkXLvajeiQn+67syKWyvjzLv3bRIOLl0oZhgNixJ27WgIAB6q+iNgLMyZc50SZM0sxBxM2Asre9DsKX1ehQyCb6sQK1y0yT/F/MqVptOpBWAOSimB25UOpghKpA7ng1icweTIhxriOoYV/LBm0yBWAbpfP2PZ3GLx/0CkJeqUjvUr57+WEZRQiLQkBhtCYi1pe5TyE8vWO4mk+yDvsnDLVrqGS3u3SOQ3qtDhIOGqKDqoTp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cert-manager-secrets
      namespace: network
    type: Opaque
