apiVersion: v2
name: cert-manager
description: Mod chart for cert-manager with AVP support
type: application
version: 0.1.0

dependencies:
- name: cert-manager
  version: "v1.18.1"
  repository: "https://charts.jetstack.io"
