apiVersion: v2
name: certmanager
description: Mod chart for cert-manager with AVP support
type: application
version: 0.1.0

dependencies:
- name: cert-manager
  version: "v1.18.2"
  repository: "https://charts.jetstack.io"
