#!/bin/bash

set -eu

dry_run_mode="none"

while getopts "d" flag; do
    case $flag in
    d)
        echo "Running dry-run mode..."
        dry_run_mode="server"
        ;;
    \?)
        echo "Wrong argument"
        exit 1
        ;;
    esac
done

# Add helm repositories
helm repo add jetstack https://charts.jetstack.io && \
    helm repo add mittwald https://helm.mittwald.de && \
    helm repo update

project_path="$(git rev-parse --show-toplevel)"

# common
echo -e "\nDeploying common..."
common_dir="${project_path}/common"

kubectl apply -f "${common_dir}"/00-namespace.yaml

echo -e "Done!\n"

# replicator
echo -e "\nDeploying replicator..."

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade --install --namespace default kubernetes-replicator mittwald/kubernetes-replicator --dry-run="server"
else
    helm upgrade --install --namespace default kubernetes-replicator mittwald/kubernetes-replicator
fi

echo -e "Done!\n"

# traefik
echo -e "\nDeploying traefik..."
traefik_dir="${project_path}/traefik"

# Replace env variables
envsubst <"${traefik_dir}"/02-ingress-route.yaml | sponge "${traefik_dir}"/02-ingress-route.yaml

kubectl apply -f "${traefik_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"

# cert-manager
echo -e "\nDeploying cert-manager..."
certmanager_dir="${project_path}/certmanager"

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade --install \
        cert-manager jetstack/cert-manager \
        --namespace cert-manager \
        --create-namespace \
        --set crds.enabled=true \
        --dry-run="server"   
else
    helm upgrade --install \
        cert-manager jetstack/cert-manager \
        --namespace cert-manager \
        --create-namespace \
        --set crds.enabled=true
fi

# Replace env variables
envsubst <"${certmanager_dir}"/01-issuer.yaml | sponge "${certmanager_dir}"/01-issuer.yaml
envsubst <"${certmanager_dir}"/02-certificate.yaml | sponge "${certmanager_dir}"/02-certificate.yaml

kubectl apply -f "${certmanager_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"

# metallb
#kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml --dry-run="${dry_run_mode}"

#kubectl apply -f "${project_path}/metallb" --dry-run="${dry_run_mode}"

# adguard
echo -e "\nDeploying adguard..."
adguard_dir="${project_path}/adguard"

# Replace env variables
envsubst <"${adguard_dir}"/05-ingress-route.yaml | sponge "${adguard_dir}"/05-ingress-route.yaml

#kubectl apply -f "${adguard_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"
