#!/bin/bash

set -eu

dry_run_mode="none"

while getopts "d" flag; do
    case $flag in
    d)
        echo "Running dry-run mode..."
        dry_run_mode="server"
        ;;
    \?)
        echo "Wrong argument"
        exit 1
        ;;
    esac
done

# Add helm repositories
helm repo add traefik https://traefik.github.io/charts && \
    helm repo add jetstack https://charts.jetstack.io && \
    helm repo add mittwald https://helm.mittwald.de && \
    helm repo add metallb https://metallb.github.io/metallb && \
    helm repo update

project_path="$(git rev-parse --show-toplevel)"

# common
echo -e "\nDeploying common..."
common_dir="${project_path}/common"

kubectl apply -f "${common_dir}"/00-namespace.yaml

echo -e "Done!\n"

# replicator
echo -e "\nDeploying replicator..."
replicator_dir="${project_path}/replicator"

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade --install --namespace default kubernetes-replicator mittwald/kubernetes-replicator --values "${replicator_dir}"/helm/values.yaml --dry-run="server"
else
    helm upgrade --install --namespace default kubernetes-replicator mittwald/kubernetes-replicator --values "${replicator_dir}"/helm/values.yaml
fi

echo -e "Done!\n"

# traefik
echo -e "\nDeploying traefik..."
traefik_dir="${project_path}/traefik"

# Replace env variables
envsubst <"${traefik_dir}"/01-ingress-route.yaml | sponge "${traefik_dir}"/01-ingress-route.yaml

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade --install traefik traefik/traefik --namespace network --set crds.enabled=true --values "${traefik_dir}"/helm/values.yaml --dry-run="server"
else
    helm upgrade --install traefik traefik/traefik --namespace network --set crds.enabled=true --values "${traefik_dir}"/helm/values.yaml
fi

kubectl apply -f "${traefik_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"

# cert-manager
echo -e "\nDeploying cert-manager..."
certmanager_dir="${project_path}/certmanager"

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade --install cert-manager jetstack/cert-manager --namespace network --set crds.enabled=true --values "${certmanager_dir}"/helm/values.yaml --dry-run="server"
else
    helm upgrade --install cert-manager jetstack/cert-manager --namespace network --set crds.enabled=true --values "${certmanager_dir}"/helm/values.yaml
fi

# Replace env variables
envsubst <"${certmanager_dir}"/01-issuer.yaml | sponge "${certmanager_dir}"/01-issuer.yaml
envsubst <"${certmanager_dir}"/02-certificate.yaml | sponge "${certmanager_dir}"/02-certificate.yaml

kubectl apply -f "${certmanager_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"

# metallb
echo -e "\nDeploying metallb..."
metallb_dir="${project_path}/metallb"

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade --install metallb metallb/metallb --namespace network --values "${metallb_dir}"/helm/values.yaml --dry-run="server"
else
    helm upgrade --install metallb metallb/metallb --namespace network --values "${metallb_dir}"/helm/values.yaml
fi

# Wait for metallb to be ready
kubectl wait --namespace network --for=condition=ready pod -l app=metallb-controller --timeout=60s

kubectl apply -f "${metallb_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"
