#!/bin/bash

set -e

project_path="$(git rev-parse --show-toplevel)"

# cert-manager
namespace="cert-manager"
input_secret="${project_path}/certmanager/00-secret.plain.yaml"
output_secret="${project_path}/certmanager/00-secret.yaml"

cert_file=$1

if [[ ! -f "${cert_file}" ]]; then
  echo "[!] Certificate ${CERT_FILE} not found!"
  exit 1
fi

echo "🔐 Signing ${input_secret} for namespace: '${namespace}'..."

sealed_secret="$(kubeseal \
  --cert "${cert_file}" \
  --format yaml \
  --scope namespace-wide \
  --namespace "${namespace}" \
  < "${input_secret}")"

echo "${sealed_secret}" > "${output_secret}"

echo "[+] Sealed secret created and saved to ${output_secret}"
